/* The following code was generated by JFlex 1.7.0 */

/* User Code */
import java_cup.runtime.*; // defines the Symbol class
import java.util.LinkedList;
import support.*;
import ast.base.*;
import ast.decl.*;
import ast.type.*;
import ast.stmt.*;
import ast.expr.*;

// The generated scanner will return a Symbol for each token that it finds.
// A Symbol contains an Object field named value; that field will be of type
// TokenVal, defined below.
//
// A TokenVal object contains the line number on which the token occurs as
// well as the number of the character on that line that starts the token.
// Some tokens (e.g., literals) also include the value of the token.

class TokenVal {
 // fields
    public int linenum;
    public int charnum;
 // constructor
    TokenVal(int l, int c) {
        linenum = l;
				charnum = c;
    }
}
class IdTokenVal extends TokenVal {
	  // new field: the name of the identifier
		public String idVal;
 		// constructor
		IdTokenVal(int l, int c, String name) {
				super(l,c);
				idVal = name;
		}
}

class IntLitTokenVal extends TokenVal {
 // new field: the value of the integer literal
    public int intVal;
 // constructor
    IntLitTokenVal(int l, int c, int val) {
        super(l,c);
				intVal = val;
    }
}

class StringTokenVal extends TokenVal {
 // new field: the value of the integer literal
    public String str;
 // constructor
    StringTokenVal(int l, int c, String val) {
        super(l,c);
				str = val;
    }
}

// The following class is used to keep track of the character number at which
// the current token starts on its line.
class CharNum {
  static int num=1;
}
/* Options and declarations */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>simple.jlex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int BLOCKCOMMENT = 2;
  public static final int SLCOMMENT = 4;
  public static final int STRING = 6;
  public static final int STRING_ESCAPE = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\54\1\55\1\55\1\53\22\0\1\1\1\25\1\51"+
    "\1\45\1\0\1\22\1\26\1\0\1\6\1\6\1\20\1\17\1\27"+
    "\1\17\1\50\1\21\1\5\11\3\1\0\1\30\1\23\1\24\1\23"+
    "\2\0\13\2\1\2\1\2\1\2\4\2\1\42\1\2\1\2\5\2"+
    "\1\0\1\52\1\0\1\45\1\2\1\0\1\14\1\40\1\36\1\34"+
    "\1\12\1\13\1\43\1\33\1\31\2\2\1\15\1\47\1\41\1\35"+
    "\1\37\1\2\1\10\1\16\1\7\1\11\1\44\1\32\1\2\1\46"+
    "\1\2\1\6\1\4\1\6\7\0\1\55\u1fa2\0\1\55\1\55\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\1\1\1\4\1\5"+
    "\5\3\3\6\1\7\1\10\1\11\1\1\1\12\1\13"+
    "\10\3\1\14\2\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\11\6\3\1\25\1\26\1\7\1\27"+
    "\11\3\1\30\6\3\1\31\10\3\1\32\17\3\1\33"+
    "\1\34\3\3\13\0\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u019e\0\346\0\346\0\u01cc\0\u01fa\0\u0228\0\u0256"+
    "\0\u0284\0\u02b2\0\346\0\u02e0\0\u030e\0\u030e\0\u030e\0\u033c"+
    "\0\346\0\346\0\u036a\0\u0398\0\u03c6\0\u03f4\0\u0422\0\u0450"+
    "\0\u047e\0\u04ac\0\346\0\346\0\u04da\0\346\0\346\0\u0508"+
    "\0\u0508\0\346\0\346\0\346\0\346\0\u0536\0\u0564\0\u0592"+
    "\0\u05c0\0\u05ee\0\u061c\0\346\0\346\0\346\0\u0142\0\u064a"+
    "\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba"+
    "\0\346\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u0142"+
    "\0\u08fc\0\u092a\0\u0958\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u0a3e"+
    "\0\u0142\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52\0\u0b80"+
    "\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66\0\u0c94\0\u0cc2\0\u0cf0"+
    "\0\u0142\0\u0142\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04"+
    "\0\u0e32\0\u0e60\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18\0\u0f46\0\u0f74"+
    "\0\346";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\10\1\17\1\20\2\10\1\21\1\22\1\23"+
    "\1\24\1\23\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\10\1\35\1\10\1\36\1\37\1\40"+
    "\1\10\1\41\1\10\1\42\1\6\2\10\1\6\1\43"+
    "\1\6\2\7\1\0\1\44\1\7\16\44\1\45\32\44"+
    "\2\7\1\0\53\46\1\0\1\47\1\0\26\50\1\51"+
    "\16\50\1\51\3\50\1\52\1\53\2\0\1\50\4\0"+
    "\1\54\3\0\1\54\30\0\1\54\73\0\1\7\51\0"+
    "\2\7\3\0\2\10\1\0\1\10\1\0\10\10\12\0"+
    "\14\10\1\0\2\10\11\0\1\11\1\0\1\11\53\0"+
    "\1\11\1\55\1\13\52\0\2\10\1\0\1\10\1\0"+
    "\1\10\1\56\6\10\12\0\14\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\3\10\1\57\4\10\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\6\10\1\60\1\10\12\0\14\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\5\10\1\61\2\10\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\1\62\7\10\12\0\1\10\1\63\12\10\1\0\2\10"+
    "\11\0\1\11\1\0\1\13\70\0\1\64\1\65\60\0"+
    "\1\66\57\0\1\55\31\0\2\10\1\0\1\10\1\0"+
    "\4\10\1\67\3\10\12\0\10\10\1\70\3\10\1\0"+
    "\2\10\10\0\2\10\1\0\1\10\1\0\10\10\12\0"+
    "\2\10\1\71\11\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\3\10\1\72\4\10\12\0\4\10\1\67"+
    "\7\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\5\10\1\60\1\73\1\10\12\0\14\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\2\10\1\74\5\10"+
    "\12\0\14\10\1\0\2\10\10\0\2\10\1\0\1\10"+
    "\1\0\10\10\12\0\4\10\1\75\7\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\1\76\7\10\12\0"+
    "\14\10\1\0\1\77\1\10\10\0\2\10\1\0\1\10"+
    "\1\0\10\10\12\0\4\10\1\100\7\10\1\0\2\10"+
    "\27\0\1\101\34\0\51\50\4\0\1\50\2\0\2\10"+
    "\1\0\1\10\1\0\2\10\1\102\5\10\12\0\14\10"+
    "\1\0\2\10\10\0\2\10\1\0\1\10\1\0\1\103"+
    "\7\10\12\0\14\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\7\10\1\104\12\0\14\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\6\10\1\105\1\10"+
    "\12\0\14\10\1\0\2\10\10\0\2\10\1\0\1\10"+
    "\1\0\5\10\1\106\2\10\12\0\14\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\10\10\12\0\1\107"+
    "\13\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\1\110\7\10\12\0\14\10\1\0\2\10\10\0\2\10"+
    "\1\0\1\10\1\0\10\10\12\0\1\111\13\10\1\0"+
    "\2\10\10\0\2\10\1\0\1\10\1\0\4\10\1\112"+
    "\3\10\12\0\14\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\5\10\1\113\2\10\12\0\14\10\1\0"+
    "\2\10\10\0\2\10\1\0\1\10\1\0\10\10\12\0"+
    "\7\10\1\114\4\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\10\10\12\0\4\10\1\115\7\10\1\0"+
    "\2\10\10\0\2\10\1\0\1\10\1\0\1\10\1\116"+
    "\6\10\12\0\14\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\7\10\1\117\12\0\14\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\10\10\12\0\1\120"+
    "\13\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\3\10\1\121\4\10\12\0\14\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\2\10\1\122\5\10\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\3\10\1\67\4\10\12\0\14\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\7\10\1\102\12\0\14\10"+
    "\1\0\2\10\10\0\2\10\1\0\1\10\1\0\1\123"+
    "\7\10\12\0\14\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\1\124\7\10\12\0\14\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\6\10\1\104\1\10"+
    "\12\0\14\10\1\0\2\10\10\0\2\10\1\0\1\10"+
    "\1\0\5\10\1\125\2\10\12\0\14\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\7\10\1\126\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\6\10\1\123\1\10\12\0\14\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\6\10\1\127\1\10\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\10\10\12\0\1\130\13\10\1\0\2\10\10\0\2\10"+
    "\1\0\1\10\1\0\1\131\7\10\12\0\14\10\1\0"+
    "\2\10\10\0\2\10\1\0\1\10\1\0\10\10\12\0"+
    "\3\10\1\110\10\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\1\10\1\132\6\10\12\0\14\10\1\0"+
    "\2\10\10\0\2\10\1\0\1\10\1\0\10\10\12\0"+
    "\1\133\13\10\1\0\2\10\10\0\2\10\1\0\1\10"+
    "\1\0\10\10\12\0\5\10\1\134\6\10\1\0\2\10"+
    "\10\0\2\10\1\0\1\10\1\0\2\10\1\135\5\10"+
    "\12\0\14\10\1\0\2\10\10\0\2\10\1\0\1\10"+
    "\1\0\7\10\1\110\12\0\14\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\3\10\1\136\4\10\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\10\10\12\0\10\10\1\137\3\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\3\10\1\140\4\10\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\10\10\12\0\10\10\1\141\3\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\10\10\12\0\5\10\1\142"+
    "\6\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\10\10\12\0\2\10\1\67\11\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\6\10\1\143\1\10\12\0"+
    "\14\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\5\10\1\144\2\10\12\0\14\10\1\0\2\10\10\0"+
    "\2\10\1\0\1\10\1\0\10\10\12\0\12\10\1\110"+
    "\1\10\1\0\2\10\10\0\2\10\1\0\1\10\1\0"+
    "\10\10\12\0\14\10\1\0\1\10\1\145\10\0\2\10"+
    "\1\0\1\10\1\0\1\67\7\10\12\0\14\10\1\0"+
    "\2\10\10\0\2\10\1\0\1\10\1\0\10\10\12\0"+
    "\10\10\1\110\3\10\1\0\2\10\10\0\2\10\1\0"+
    "\1\10\1\0\10\10\12\0\14\10\1\0\2\10\1\146"+
    "\42\0\1\147\31\0\1\150\53\0\1\151\116\0\1\152"+
    "\44\0\1\153\26\0\1\154\76\0\1\155\65\0\1\156"+
    "\23\0\1\157\63\0\1\160\101\0\1\161\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4002];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\4\1\2\11\6\1\1\11\5\1\2\11"+
    "\10\1\2\11\1\1\2\11\2\1\4\11\6\1\3\11"+
    "\12\1\1\11\44\1\13\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
		//it's a stack - each new string gets pushed on top
    LinkedList<StringBuilder> stringBuffers = new LinkedList<StringBuilder>();

		//found out its probably not needed, however don't want to remove it :D 
		//probably everythings stored in StringTokenVal anyway


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case BLOCKCOMMENT: {
              Errors.fatal(yyline+1, CharNum.num,"Unterminated comment at EOF");
		yybegin(YYINITIAL);
            }  // fall though
            case 114: break;
            case SLCOMMENT: {
              Errors.fatal(yyline+1, CharNum.num,"Unterminated single line comment at EOF");
		yybegin(YYINITIAL); // Return to the initial state
            }  // fall though
            case 115: break;
            case STRING: {
              System.out.println("Unterminated string literal at EOF");
		System.out.println("Read until EOF: " + stringBuffers.get(stringBuffers.size() - 1).toString());
		Errors.fatal(yyline+1, CharNum.num,
					"Unterminated string literal at EOF");
		yybegin(YYINITIAL); // Return to the initial state
            }  // fall though
            case 116: break;
            default:
          { 						return new Symbol(sym.EOF); 
 }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { Errors.fatal(yyline+1, CharNum.num, "ignoring illegal character: " + yytext());
	CharNum.num++;
            } 
            // fall through
          case 30: break;
          case 2: 
            { CharNum.num += yytext().length();
            } 
            // fall through
          case 31: break;
          case 3: 
            { System.out.println("Found identifier named: " + yytext());
	Symbol S = new Symbol(sym.ID, new IdTokenVal(yyline+1, CharNum.num, yytext()));
	CharNum.num += yytext().length();
	return S;
            } 
            // fall through
          case 32: break;
          case 4: 
            { // NOTE: the following computation of the integer value does NOT
	    //       check for overflow.  This must be changed.
			System.out.println("Found an integer literal: " + yytext());	
	    long val = Long.parseLong(yytext());
	    Symbol S = new Symbol(sym.INTLITERAL, new IntLitTokenVal(yyline+1, CharNum.num, (int) val));
	    CharNum.num += yytext().length();
	    return S;
            } 
            // fall through
          case 33: break;
          case 5: 
            { Symbol BracketSymbol = null;
	switch(yytext()) {
		case "(":
				System.out.println("Found an open parenthesis");
				BracketSymbol = new Symbol(sym.LPAREN, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return BracketSymbol;
		case ")":
				System.out.println("Found a closed parenthesis");
				BracketSymbol = new Symbol(sym.RPAREN, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return BracketSymbol;
		case "{":
				System.out.println("Found an open curly brace");
				BracketSymbol = new Symbol(sym.LCURLY, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return BracketSymbol;
		case "}":
				System.out.println("Found a closed curly brace");
				BracketSymbol = new Symbol(sym.RCURLY, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return BracketSymbol;
		default:
				// should not be reached
				break;
	}
            } 
            // fall through
          case 34: break;
          case 6: 
            { Symbol AOpsSymbol = null;
	switch (yytext()) {
		case "+":
			System.out.println("Found a plus operator");
			AOpsSymbol = new Symbol(sym.PLUS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
		case "-":
			System.out.println("Found a minus operator");
			AOpsSymbol = new Symbol(sym.MINUS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
		case "*":
			System.out.println("Found a multiplication operator");
			AOpsSymbol = new Symbol(sym.TIMES, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
		case "/":
			System.out.println("Found a division operator");
			AOpsSymbol = new Symbol(sym.DIVIDE, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
			
		default:
			//shouldn't be reached
			break;
	}
            } 
            // fall through
          case 35: break;
          case 7: 
            { Symbol ROpsSymbol = null;
	switch (yytext()) {
		case "<":
			System.out.println("Found a less-than operator");
			ROpsSymbol = new Symbol(sym.LESS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case ">":
			System.out.println("Found a greater-than operator");
			ROpsSymbol = new Symbol(sym.GREATER, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case "<=":
			System.out.println("Found a less-than-or-equal operator");
			ROpsSymbol = new Symbol(sym.LESSEQ, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case ">=":
			System.out.println("Found a greater-than-or-equal operator");
			ROpsSymbol = new Symbol(sym.GREATEREQ, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case "==":
			System.out.println("Found an equality operator");
			ROpsSymbol = new Symbol(sym.EQUALS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case "!=":
			System.out.println("Found a not-equal operator");
			ROpsSymbol = new Symbol(sym.NOTEQUALS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
			
		default:
			//shouldn't be reached
			break;
	}
            } 
            // fall through
          case 36: break;
          case 8: 
            { System.out.println("Found an assignment operator");
	Symbol assign = new Symbol(sym.ASSIGN, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return assign;
            } 
            // fall through
          case 37: break;
          case 9: 
            { Symbol LOpsSymbol = null;
	switch (yytext()) {
		case "&&":
			System.out.println("Found a logical AND operator");
			LOpsSymbol = new Symbol(sym.AND, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return LOpsSymbol;
		case "||":
			System.out.println("Found a logical OR operator");
			LOpsSymbol = new Symbol(sym.OR, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return LOpsSymbol;
		case "!":
			System.out.println("Found a logical NOT operator");
			LOpsSymbol = new Symbol(sym.NOT, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return LOpsSymbol;
			
		default:
			//shouldn't be reached
			break;
	}
            } 
            // fall through
          case 38: break;
          case 10: 
            { System.out.println("Found a comma");
	Symbol comma = new Symbol(sym.COMMA, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return comma;
            } 
            // fall through
          case 39: break;
          case 11: 
            { System.out.println("Found a semicolon");
	Symbol semicolon = new Symbol(sym.SEMICOLON, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return semicolon;
            } 
            // fall through
          case 40: break;
          case 12: 
            { System.out.println("Start of a parsing string literal..");
		stringBuffers.add(new StringBuilder()); 
    yybegin(STRING); // Switch to STRING state
            } 
            // fall through
          case 41: break;
          case 13: 
            { CharNum.num += yytext().length(); // Consume any other characters inside comments
            } 
            // fall through
          case 42: break;
          case 14: 
            { CharNum.num += yytext().length(); // Consume charcters in single-line comment
            } 
            // fall through
          case 43: break;
          case 15: 
            { System.out.println("End of single-line comment");
				CharNum.num += yytext().length(); // Consume the newline character
				yybegin(YYINITIAL);
            } 
            // fall through
          case 44: break;
          case 16: 
            { stringBuffers.get(stringBuffers.size() - 1).append(yytext());
    CharNum.num += yytext().length(); // Consme any other characters inside strings
            } 
            // fall through
          case 45: break;
          case 17: 
            { //error illegal character in string
		Errors.fatal(yyline+1, CharNum.num,
					"illegal character in string: " + yytext());
            } 
            // fall through
          case 46: break;
          case 18: 
            { System.out.println("Resulting string literal: " + stringBuffers.get(stringBuffers.size() - 1).toString());
    yybegin(YYINITIAL); // Return to the initial state
    Symbol S = new Symbol(sym.STRINGLITERAL, new StringTokenVal(yyline+1, CharNum.num, stringBuffers.get(stringBuffers.size() - 1).toString()));
		CharNum.num += yytext().length();
    return S;
            } 
            // fall through
          case 47: break;
          case 19: 
            { //should work without - don't know why it doesn't
	yybegin(STRING_ESCAPE);
            } 
            // fall through
          case 48: break;
          case 20: 
            { System.out.println("Unterminated string literal" );

		switch(yytext()) {
			case "n":
				System.out.println("Found newline escape sequence");
				stringBuffers.get(stringBuffers.size() - 1).append('\n');
				CharNum.num += 2; // Reset character number at the start of a new line
				break;
			case "r":
				System.out.println("Found carriage return escape sequence");
				stringBuffers.get(stringBuffers.size() - 1).append('\r');
				CharNum.num += 2; // Reset character number at the start of a new line
				break;
			default: 
				// shouldn't be reached 
				break;
		}
		
    yybegin(STRING);
            } 
            // fall through
          case 49: break;
          case 21: 
            { yybegin( BLOCKCOMMENT);
			CharNum.num += 2;
            } 
            // fall through
          case 50: break;
          case 22: 
            { yybegin(SLCOMMENT);
			CharNum.num += 2;
            } 
            // fall through
          case 51: break;
          case 23: 
            { Symbol FlowKeyWordSymbol = null;
  switch (yytext()) {
		case "if":
				System.out.println("Found an if");
				FlowKeyWordSymbol = new Symbol(sym.IF, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "else":
				System.out.println("Found an else");
				FlowKeyWordSymbol = new Symbol(sym.ELSE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "while":
				System.out.println("Found a while");
				FlowKeyWordSymbol = new Symbol(sym.WHILE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "do":
				System.out.println("Found a do");
				FlowKeyWordSymbol = new Symbol(sym.DO, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "switch":
				System.out.println("Found a switch");
				FlowKeyWordSymbol = new Symbol(sym.SWITCH, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "case":
				System.out.println("Found a case");
				FlowKeyWordSymbol = new Symbol(sym.CASE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "default":
				System.out.println("Found a default");
				FlowKeyWordSymbol = new Symbol(sym.DEFAULT, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		default:
				// should not be reached
				break;
	}
            } 
            // fall through
          case 52: break;
          case 24: 
            { yybegin(YYINITIAL);
			CharNum.num += 2;
            } 
            // fall through
          case 53: break;
          case 25: 
            { Symbol TypeSymbol = null;
	switch(yytext()) {
		case "int":
				System.out.println("Found type int");
				TypeSymbol = new Symbol(sym.INT, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "boolean":
				System.out.println("Found type boolean");
				TypeSymbol = new Symbol(sym.BOOLEAN, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "String":
				System.out.println("Found type String");
				TypeSymbol = new Symbol(sym.STRING, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "class":
				System.out.println("Found class keyword");
				TypeSymbol = new Symbol(sym.CLASS, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "void":
				System.out.println("Found void keyword");
				//TypeSymbol = new Symbol(sym.VOID, new TokenVal(yyline+1, CharNum.num));
				TypeSymbol = new Symbol(sym.VOID, new VoidNode());
				CharNum.num += yytext().length();
				return TypeSymbol;
		default:
				// should not be reached
				break;
	}
            } 
            // fall through
          case 54: break;
          case 26: 
            { Symbol ValueSymbol = null;
	switch(yytext()) {
		case "true":
				System.out.println("Found boolean literal true");
				ValueSymbol = new Symbol(sym.TRUE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return ValueSymbol;
		case "false":
				System.out.println("Found boolean literal false");
				ValueSymbol = new Symbol(sym.FALSE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return ValueSymbol;
		default:
				// should not be reached
				break;
	}
            } 
            // fall through
          case 55: break;
          case 27: 
            { System.out.println("Found a return");
	Symbol S = new Symbol(sym.RETURN, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return S;
            } 
            // fall through
          case 56: break;
          case 28: 
            { Symbol ScopeOpSymbol = null;
	switch (yytext()) {
		case "public":
			System.out.println("Found public scope operator");
			ScopeOpSymbol = new Symbol(sym.PUBLIC, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ScopeOpSymbol;
		case "static":
			System.out.println("Found static scope operator");
			ScopeOpSymbol = new Symbol(sym.STATIC, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ScopeOpSymbol;
			
		default:
			//shouldn't be reached
			break;
	}
            } 
            // fall through
          case 57: break;
          case 29: 
            { System.out.println("Found a println");
	Symbol S = new Symbol(sym.PRINT, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return S;
            } 
            // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
