/**********************************************************************
 Java CUP specification for a parser for Simple programs
 **********************************************************************/

import java_cup.runtime.*;
import support.*;
import ast.base.*;
import ast.decl.*;
import ast.type.*;
import ast.stmt.*;
import ast.expr.*;

parser code {:
   public void report_error(String message, Object info) {
        int line = 0;
        int column = 0;
        StringBuilder m = new StringBuilder("");
        if (info instanceof java_cup.runtime.Symbol) {
							java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
							String tokenName = sym.terminalNames[s.sym];
							// Special case EOF token program
							if (s.sym != sym.EOF) {
							line = ((TokenVal) s.value).linenum;
							column = ((TokenVal) s.value).charnum;
        }
        m.append(" : " + message + " - Token: " + tokenName + " value " + s.value);
        }
        Errors.fatal(line, column, m.toString());
    }
:};



/* Terminals (tokens returned by the scanner) */
terminal PUBLIC;
terminal CLASS;
terminal STATIC;
terminal IntNode INT;
terminal BooleanNode BOOLEAN;
terminal StringNode STRING;
terminal VoidNode VOID; // VoidNode was added.. try to comprehend why it did not exist..
terminal TokenVal TRUE;
terminal TokenVal FALSE;
terminal IfStmtNode IF;
terminal IfElseStmtNode ELSE;
terminal WhileStmtNode WHILE;
terminal WhileStmtNode DO;
terminal PrintStmtNode PRINT;
terminal ReturnStmtNode RETURN;
terminal IdTokenVal     ID;
terminal IntLitTokenVal INTLITERAL;
terminal StringTokenVal STRINGLITERAL; // changed to StringTokenVal
terminal AssignStmtNode ASSIGN;


terminal TokenVal       LCURLY, RCURLY;
terminal TokenVal       LPAREN, RPAREN;

terminal COMMA;
terminal SEMICOLON;
terminal PLUS, MINUS, TIMES, DIVIDE;
terminal NOT, AND, OR;
terminal EQUALS, NOTEQUALS, LESS, GREATER, LESSEQ, GREATEREQ;

terminal SWITCH;
terminal CASE;
terminal DEFAULT;

/* Non-terminals
 *
 * NOTE: You will need to add more nonterminals to this list as you
 *       add productions to the grammar below.
 */
non terminal stmt;

non terminal ProgramNode      program;
non terminal ClassBodyNode    classBody;
non terminal DeclNode	      	decl;
non terminal FieldDeclNode    fieldDecl;
non terminal TypeNode	     		type;
non terminal IdNode	      		id;

non terminal MethodDeclNode   methodDecl;
non terminal FormalDeclNode   formalDecl;
non terminal MethodBodyNode   methodBody;
non terminal VarDeclNode      varDecl;

non terminal Sequence 				actualList;
non terminal Sequence         declList;
non terminal Sequence         varDeclList;
non terminal Sequence 				formalsList;
non terminal Sequence         stmtList;
non terminal Sequence 				switchGroupList;

non terminal FormalsListNode  formals;
non terminal CaseStmtNode 		switchGroup;
non terminal switchLabel;
non terminal ExpNode          exp;


precedence left OR;
precedence left AND;
precedence nonassoc LESS, GREATER, LESSEQ, GREATEREQ, EQUALS, NOTEQUALS;
precedence left PLUS, MINUS; 
precedence left TIMES, DIVIDE; // Assoziativität links

precedence right NOT, MINUS; // Unary minus


 
start with program;

/*
 * grammar with actions
 *
 * add more here
 */

program		::= PUBLIC CLASS id:a LCURLY classBody:b RCURLY
			{: RESULT = new ProgramNode(a, b); :}
		;

classBody	::= declList:e
		{: RESULT = new ClassBodyNode(new DeclListNode(e)); :}
		;

declList 	::= 	declList:a decl:b
		{: 
			System.out.println("Values of declList: " + a.toString());
			System.out.println("Adding declaration to declList is actually " + a);
			a.addToEnd(b);
			RESULT = a;
		:}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

decl	::= fieldDecl:e
		{: RESULT = e; :}
		| methodDecl:e
		{: RESULT = e; :}
		;

fieldDecl	::= STATIC type:e0 id:e1 SEMICOLON
		{: RESULT = new FieldDeclNode((TypeNode) e0, (IdNode) e1); :}
		;

methodDecl	::= PUBLIC STATIC VOID id:b formals:c methodBody:d // no return value
								{: RESULT = new MethodDeclNode(new VoidNode(), b, c, d); :} //cannot be sure that VOID:a would be a TypeNode
                | PUBLIC STATIC INT id:b formals:c  methodBody:d // int return value allowed
								{: RESULT = new MethodDeclNode(new IntNode() , b, c, d); :}
                | VOID id:b formals:c methodBody:d // void method without public static
								{: RESULT = new MethodDeclNode(new VoidNode(), b, c, d); :}
                | INT id:b formals:c methodBody:d // int method without public static
								{: RESULT = new MethodDeclNode(new IntNode(), b, c, d); :}
	        ;						


formals		::= LPAREN RPAREN
		{: RESULT = new FormalsListNode(new Sequence()); :}
		| LPAREN formalsList:fl RPAREN
		{: RESULT = new FormalsListNode(fl); :}
		;

formalsList	::= formalDecl:e0
		{: 
			var x = new Sequence();
			x.addToFront(e0);
			System.out.println("Create new formalsList RESULT: " + x.toString());
			RESULT = x;
		:}
		| formalDecl:e0 COMMA formalsList:e1
		{: 
			if(e1 == null) {
				var x = new Sequence();
				x.addToFront(e0);
				System.out.println("Create new formalsList RESULT: " + x.toString());
				RESULT = x;
			} else
			{ 
				e1.addToFront(e0);
				RESULT = e1;
			}
			System.out.println("formalsList RESULT: " + RESULT.toString());
		
		:}
		;

formalDecl	::= type:e0 id:e1
		{: RESULT = new FormalDeclNode(e0, e1 ); :}
		;
methodBody	::= LCURLY varDeclList:e0 stmtList:e1 RCURLY 
		{: RESULT = new MethodBodyNode(new DeclListNode(e0), new StmtListNode(e1)); :}
		;

varDeclList	::= varDeclList:e0 varDecl:e1
		{: e0.addToEnd(e1);
				RESULT = e0;
		
		 :}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

varDecl		::= type:e0 id:e1  SEMICOLON
		{: RESULT = new VarDeclNode(e0, e1 ); :}
		;

stmtList	::= stmtList:e0 stmt:e1
		{: RESULT = e0; RESULT.addToEnd(e1); :}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;


/* the following rules are for the switch / case statement */

switchGroupList   ::= switchGroupList:e0 switchGroup:e1
		{: e0.addToEnd(e1);
			 RESULT = e0; 
		 :}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

switchGroup	::=   switchLabel:e0 stmtList:e1
		{: RESULT = new CaseStmtNode( 
				(ExpNode) e0, new StmtListNode(e1)
		); :}
		;

switchLabel	::=   CASE exp:e COMMA
		{: RESULT = e; :}
		| DEFAULT COMMA
		;      
		     
stmt		::= 	
					PRINT LPAREN exp:e1 RPAREN SEMICOLON 
					{: RESULT = new PrintStmtNode(e1); :}
					
					| id:e1 ASSIGN exp:e2 SEMICOLON
					{: RESULT = new AssignStmtNode(e1, e2); :}

	        | IF LPAREN exp:a RPAREN LCURLY stmtList:b RCURLY
					{: RESULT = new IfStmtNode(a, new StmtListNode(b)); :}

	        | IF LPAREN exp:a RPAREN LCURLY stmtList:b RCURLY ELSE LCURLY stmtList:c RCURLY
					{: RESULT = new IfElseStmtNode(a, new StmtListNode(b), new StmtListNode(c)); :}

	        | DO LCURLY stmtList:sl RCURLY WHILE LPAREN exp:e RPAREN 
					{: RESULT = new WhileStmtNode(e, new StmtListNode( sl )); :}	

					| RETURN SEMICOLON
					| RETURN exp:e0 SEMICOLON // return with a value
					{: RESULT = new ReturnExprStmtNode(e0); :}
					| id:e0 LPAREN RPAREN SEMICOLON  	  // function call with no args
					{: RESULT = new CallStmtNode(e0, new ExpListNode(new Sequence())); :}
	        | id:e0 LPAREN actualList:e1 RPAREN SEMICOLON // with args
					{: RESULT = new CallStmtNode(e0, new ExpListNode(e1)); :}
					| LCURLY varDeclList stmtList RCURLY  // nested block
					{: RESULT = new MethodBodyNode(new DeclListNode(new Sequence()), new StmtListNode(new Sequence())); :}

					| SWITCH LPAREN exp:ex RPAREN LCURLY switchGroupList:sg RCURLY
					{: RESULT = new SwitchStmtNode(ex, new SwitchGroupListNode(sg)) ; :}
					;


exp		::= 
		exp:e0 PLUS exp:e1
		{: RESULT = new PlusNode(e0, e1); :}
	  | exp:e0 MINUS exp:e1
		{: RESULT = new MinusNode(e0, e1); :}
	  | exp:e0 TIMES exp:e1
		{: RESULT = new TimesNode(e0, e1); :}
	  | exp:e0 DIVIDE exp:e1
		{: RESULT = new DivideNode(e0, e1); :}
	  | NOT exp:e0
		{: RESULT = new NotNode(e0); :}
	  | exp:e0 AND exp:e1
		{: RESULT = new AndNode(e0, e1); :}
	  | exp:e0 OR exp:e1
		{: RESULT = new OrNode(e0, e1); :}
		| exp:e0 EQUALS exp:e1
		{: RESULT = new EqualsNode(e0, e1); :}
		| exp:e0 NOTEQUALS exp:e1
		{: RESULT = new NotEqualsNode(e0, e1); :}
		| exp:e0 LESS exp:e1
		{: RESULT = new LessNode(e0, e1); :}
		| exp:e0 GREATER exp:e1
		{: RESULT = new GreaterNode(e0, e1); :}
		| exp:e0 LESSEQ exp:e1
		{: RESULT = new LessEqNode(e0, e1); :}
		| exp:e0 GREATEREQ exp:e1
		{: RESULT = new GreaterEqNode(e0, e1); :}
		| MINUS exp:e
		{: RESULT = new UnaryMinusNode(e); :}
		| id:e
		{: RESULT = e; :}
	  | INTLITERAL:e
		{: RESULT = new IntLitNode(e.linenum, e.charnum, e.intVal); :}
	  | STRINGLITERAL:e
		{: RESULT = new StringLitNode(e.linenum, e.charnum, e.str); :}
	  | TRUE:e
		{: RESULT = new TrueNode(e.linenum, e.charnum); :}
	  | FALSE:e
		{: RESULT = new FalseNode(e.linenum, e.charnum); :}
		| LPAREN exp:e RPAREN
		{: RESULT = new ParenthesizedExpNode(e); :}
	 	| id:d LPAREN RPAREN   	      // function call with no args
		{: RESULT = new CallExprNode(d, new ExpListNode(new Sequence())); :}
	 	| id:d LPAREN actualList:e RPAREN // with args !!!added CallExprNode
		{: RESULT = new CallExprNode(d, new ExpListNode(e)); :}
		;
		
actualList	::= exp:e0
		{: 
			var x = new Sequence();
			x.addToEnd(e0);
			RESULT = x;
			:}
		| actualList:e0 COMMA exp:e1
		{: 
				e0.addToEnd(e1);
				RESULT = e0;
		:}
		;

type		::= INT {: RESULT = new IntNode(); :}
		| BOOLEAN {: RESULT = new BooleanNode(); :}
		| STRING {: RESULT = new StringNode(); :}
		| VOID {: RESULT = new VoidNode(); :}
		;

id  ::= ID:e
		{: RESULT = new IdNode(e.linenum, e.charnum, e.idVal); :}
		;




