/**********************************************************************
 Java CUP specification for a parser for Simple programs
 **********************************************************************/

import java_cup.runtime.*;

parser code {:
   public void report_error(String message, Object info) {
        int line = 0;
        int column = 0;
        StringBuilder m = new StringBuilder("");
        if (info instanceof java_cup.runtime.Symbol) {
							java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
							String tokenName = sym.terminalNames[s.sym];
							// Special case EOF token program
							if (s.sym != sym.EOF) {
							line = ((TokenVal) s.value).linenum;
							column = ((TokenVal) s.value).charnum;
        }
        m.append(" : " + message + " - Token: " + tokenName + " value " + s.value);
        }
        Errors.fatal(line, column, m.toString());
    }
:};



/* Terminals (tokens returned by the scanner) */
terminal PUBLIC;
terminal CLASS;
terminal STATIC;
terminal IntNode INT;
terminal BooleanNode BOOLEAN;
terminal StringNode STRING;
terminal VoidNode VOID; // VoidNode was added.. try to comprehend why it did not exist..
terminal TokenVal TRUE;
terminal TokenVal FALSE;
terminal IfStmtNode IF;
terminal IfElseStmtNode ELSE;
terminal WhileStmtNode WHILE;
terminal WhileStmtNode DO;
terminal PrintStmtNode PRINT;
terminal ReturnStmtNode RETURN;
terminal IdTokenVal     ID;
terminal IntLitTokenVal INTLITERAL;
terminal StringTokenVal STRINGLITERAL; // changed to StringTokenVal
terminal AssignStmtNode ASSIGN;


terminal TokenVal       LCURLY, RCURLY;
terminal TokenVal       LPAREN, RPAREN;

terminal COMMA;
terminal SEMICOLON;
terminal PLUS, MINUS, TIMES, DIVIDE;
terminal NOT, AND, OR;
terminal EQUALS, NOTEQUALS, LESS, GREATER, LESSEQ, GREATEREQ;

terminal SWITCH;
terminal CASE;
terminal DEFAULT;

/* Non-terminals
 *
 * NOTE: You will need to add more nonterminals to this list as you
 *       add productions to the grammar below.
 */
non terminal stmt;

non terminal ProgramNode      program;
non terminal ClassBodyNode    classBody;
non terminal DeclNode	      	decl;
non terminal FieldDeclNode    fieldDecl;
non terminal TypeNode	     		type;
non terminal IdNode	      		id;

non terminal MethodDeclNode   methodDecl;
non terminal FormalDeclNode   formalDecl;
non terminal MethodBodyNode   methodBody;
non terminal VarDeclNode      varDecl;

non terminal Sequence         declList;
non terminal Sequence         varDeclList;
non terminal Sequence 				formalsList;
non terminal Sequence         stmtList;

non terminal actualList;
non terminal FormalsListNode  formals;
non terminal switchGroupList;
non terminal switchGroup;
non terminal switchLabel;
non terminal ExpNode          exp;


precedence left LPAREN, RPAREN; 
precedence left OR;
precedence left AND;
precedence left EQUALS, NOTEQUALS;
precedence left LESS, GREATER, LESSEQ, GREATEREQ;
precedence left PLUS, MINUS; 
precedence left TIMES, DIVIDE; // Assoziativität links

precedence right NOT;
precedence right MINUS; // Unary minus


 
start with program;

/*
 * grammar with actions
 *
 * add more here
 */

program		::= PUBLIC CLASS id:a LCURLY classBody:b RCURLY
			{: RESULT = new ProgramNode(a, b); :}
		;

classBody	::= declList:e
		{: RESULT = new ClassBodyNode(new DeclListNode(e)); :}
		;

declList 	::= 	declList:a decl:b
		{: 
			System.out.println("Values of declList: " + a.toString());
			System.out.println("Adding declaration to declList is actually " + a);
			a.addToEnd(b);
			RESULT = a;
		:}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

decl	::= fieldDecl:e
		{: RESULT = e; :}
		| methodDecl:e
		{: RESULT = e; :}
		;

fieldDecl	::= STATIC type:e0 id:e1 SEMICOLON
		{: RESULT = new FieldDeclNode((TypeNode) e0, (IdNode) e1); :}
		;

methodDecl	::= PUBLIC STATIC VOID:a id:b formals:c methodBody:d // no return value
								{: RESULT = new MethodDeclNode(a, b, c, d); :}
                | PUBLIC STATIC INT:a id:b formals:c  methodBody:d // int return value allowed
								{: RESULT = new MethodDeclNode(a, b, c, d); :}
	        ;						

formals		::= LPAREN RPAREN
		| LPAREN formalsList:e1 RPAREN
		{: RESULT = new FormalsListNode(e1); :}
		;

formalsList	::= formalDecl
		{: RESULT = new Sequence(); RESULT.addToEnd(RESULT); :}
		| formalDecl:e0 COMMA formalsList:e1
		{: System.out.println(e1.getClass().getName());
			e1.addToFront(e0); :}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

formalDecl	::= type:e0 id:e1
		{: RESULT = new FormalDeclNode(e0, e1 ); :}
		;

methodBody	::= LCURLY varDeclList stmtList RCURLY 
		;

varDeclList	::= varDeclList varDecl
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

varDecl		::= type:e0 id:e1  SEMICOLON
		{: RESULT = new VarDeclNode(e0, e1 ); :}
		;

stmtList	::= stmtList:e0 stmt:e1
		{: RESULT = e0; RESULT.addToEnd(e1); :}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;


/* the following rules are for the switch / case statement */

switchGroupList   ::= switchGroupList switchGroup
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

switchGroup	::=   switchLabel stmtList
		;

switchLabel	::=   CASE exp COMMA
		|     				DEFAULT COMMA
		;      
		     
stmt		::= 	type:e0 id:e1 ASSIGN exp:e2 SEMICOLON
					{: RESULT = new AssignStmtNode(e0, e1, e2); :}
	        | IF LPAREN exp:a RPAREN LCURLY stmtList:b RCURLY
					{: RESULT = new IfStmtNode(a, new StmtListNode(b)); :}
	        | IF LPAREN exp:a RPAREN LCURLY stmtList:b RCURLY ELSE LCURLY stmtList:c RCURLY
					{: RESULT = new IfElseStmtNode(a, new StmtListNode(b), new StmtListNode(c)); :}
					| PRINT LPAREN exp:e1 RPAREN SEMICOLON 
					{: RESULT = new PrintStmtNode(e1); :}
					| id:e LPAREN RPAREN // function call with no args
					{: RESULT = new CallStmtNode(e, null); :}
					id:e0 LPAREN actualList:e1 RPAREN // with args 
					{: RESULT = new CallStmtNode(e0, new ExpListNode( new Sequence() )); :}
					;


exp		::= id:e
		{: RESULT = e; :}
	  | INTLITERAL:e
		{: RESULT = new IntLitNode(e.linenum, e.charnum, e.intVal); :}
	  | STRINGLITERAL:e
		{: RESULT = new StringLitNode(e.linenum, e.charnum, e.str); :}
	  | TRUE:e
		{: RESULT = new TrueNode(e.linenum, e.charnum); :}
	  | FALSE:e
		{: RESULT = new FalseNode(e.linenum, e.charnum); :}
	  | LPAREN exp:e RPAREN
		{: RESULT = e ; :}
	  | exp:e1 PLUS exp:e2
		{: RESULT = new PlusNode(e1, e2); :}
	  | exp:e1 MINUS exp:e2
		{: RESULT = new MinusNode(e1, e2); :}
	  | exp:e1 TIMES exp:e2
		{: RESULT = new TimesNode(e1, e2); :}
	  | exp:e1 DIVIDE exp:e2
		{: RESULT = new DivideNode(e1, e2); :}
	  | NOT exp:e
		{: RESULT = new NotNode(e); :}
	  | exp:e1 AND exp:e2
		{: RESULT = new AndNode(e1, e2); :}
	  | exp:e1 OR exp:e2
		{: RESULT = new OrNode(e1, e2); :}
	  | exp:e1 EQUALS exp:e2
		{: RESULT = new EqualsNode(e1, e2); :}
	  | exp:e1 NOTEQUALS exp:e2
		{: RESULT = new NotEqualsNode(e1, e2); :}
	  | exp:e1 LESS exp:e2
		{: RESULT = new LessNode(e1, e2); :}
	  | exp:e1 GREATER exp:e2
		{: RESULT = new GreaterNode(e1, e2); :}
	  | exp:e1 LESSEQ exp:e2
		{: RESULT = new LessEqNode(e1, e2); :}
	  | exp:e1 GREATEREQ exp:e2
		{: RESULT = new GreaterEqNode(e1, e2); :}

		;





actualList	::= exp:e
		| actualList:e0 COMMA exp:e1
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

type		::= INT {: RESULT = new IntNode(); :}
		| BOOLEAN {: RESULT = new BooleanNode(); :}
		| STRING {: RESULT = new StringNode(); :}
		| VOID {: RESULT = new VoidNode(); :}
		;

id  ::= ID:e
		{: RESULT = new IdNode(e.linenum, e.charnum, e.idVal); :}
		;


