/**********************************************************************
 Java CUP specification for a parser for Simple programs
 **********************************************************************/

import java_cup.runtime.*;

parser code {:
   public void report_error(String message, Object info) {
        int line = 0;
        int column = 0;
        StringBuilder m = new StringBuilder("");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            String tokenName = sym.terminalNames[s.sym];
            // Special case EOF token program
            if (s.sym != sym.EOF) {
            line = ((TokenVal) s.value).linenum;
            column = ((TokenVal) s.value).charnum;
            }
            m.append(" : " + message + " - Token: " + tokenName + " value " + s.value);
        }
        Errors.fatal(line, column, m.toString());
    }
:};



/* Terminals (tokens returned by the scanner) */
terminal PUBLIC;
terminal CLASS;
terminal STATIC;
terminal INT;
terminal BOOLEAN;
terminal STRING;
terminal VOID;
terminal TRUE;
terminal FALSE;
terminal IF;
terminal ELSE;
terminal WHILE;
terminal DO;
terminal PRINT;
terminal RETURN;
terminal IdTokenVal     ID;
terminal IntLitTokenVal INTLITERAL;
terminal StringTokenVal STRINGLITERAL; // changed to StringTokenVal


terminal TokenVal       LCURLY, RCURLY;
terminal TokenVal       LPAREN, RPAREN;

terminal COMMA;
terminal TokenVal ASSIGN;
terminal SEMICOLON;
terminal PLUS, MINUS, TIMES, DIVIDE;
terminal NOT, AND, OR;
terminal EQUALS, NOTEQUALS, LESS, GREATER, LESSEQ, GREATEREQ;

terminal SWITCH;
terminal CASE;
terminal DEFAULT;

/* Non-terminals
 *
 * NOTE: You will need to add more nonterminals to this list as you
 *       add productions to the grammar below.
 */
non terminal ProgramNode      program;
non terminal ClassBodyNode    classBody;
non terminal Sequence         declList;
non terminal DeclNode	      	decl;
non terminal FieldDeclNode    fieldDecl;
non terminal TypeNode	     		type;
non terminal IdNode	      		id;

non terminal stmt;
non terminal MethodDeclNode   methodDecl;
non terminal formals;
non terminal FormalDeclNode   formalDecl;
non terminal MethodBodyNode   methodBody;
non terminal Sequence         varDeclList;
non terminal VarDeclNode      varDecl;
non terminal Sequence         stmtList;
non terminal actualList;
non terminal switchGroupList;
non terminal switchGroup;
non terminal switchLabel;
non terminal ExpNode          exp;
non terminal formalsList;
non terminal AssignStmtNode 	assignment;


precedence left LPAREN, RPAREN; 
precedence left OR;
precedence left AND;
precedence left EQUALS, NOTEQUALS;
precedence left LESS, GREATER, LESSEQ, GREATEREQ;
precedence left PLUS, MINUS; 
precedence left TIMES, DIVIDE; // Assoziativität links

precedence right NOT;
precedence right MINUS; // Unary minus

 
start with program;

/*
 * grammar with actions
 *
 * add more here
 */

program		::= PUBLIC CLASS id:a LCURLY classBody:b RCURLY
			{: RESULT = new ProgramNode(a, b); :}
		;

classBody	::= declList
		;

declList 	::= declList decl
		| /* epsilon */
		;

decl		::= fieldDecl
		| methodDecl
		;

fieldDecl	::= STATIC type id SEMICOLON
		;

methodDecl	::= PUBLIC STATIC VOID id formals methodBody // no return value
                | PUBLIC STATIC INT id formals methodBody // int return value allowed
	        ;						

formals		::= LPAREN RPAREN
		| LPAREN formalsList RPAREN
		;

formalsList	::= formalDecl
		| formalDecl COMMA formalsList
		;

formalDecl	::= type id
		;

methodBody	::= LCURLY varDeclList stmtList RCURLY 
		;

varDeclList	::= varDeclList varDecl
		| /* epsilon */
		;

varDecl		::= type:e0 id:e1 SEMICOLON
		{: RESULT = new VarDeclNode(e0, e1 ); :}
		;

stmtList	::= stmtList stmt
		| /* epsilon */
		;


/* the following rules are for the switch / case statement */

switchGroupList   ::= switchGroupList switchGroup
		| /* epsilon */
		;

switchGroup	::=   switchLabel stmtList
		;

switchLabel	::=   CASE exp COMMA
		|     				DEFAULT COMMA
		;      
		     
stmt		::= id:e0 ASSIGN exp:e1 SEMICOLON 
	        | IF LPAREN exp RPAREN LCURLY stmtList RCURLY
	        | IF LPAREN exp RPAREN LCURLY stmtList RCURLY ELSE LCURLY stmtList RCURLY
					| PRINT LPAREN exp:e1 RPAREN SEMICOLON 
					{: RESULT = new PrintStmtNode(e1); :}
					;

exp		::= 
		| id
	  | INTLITERAL
	  | STRINGLITERAL
	  | TRUE
	  | FALSE
	  | LPAREN exp RPAREN
		;

functionCall ::= id LPAREN RPAREN // function call with no args
	  | id LPAREN actualList RPAREN // with args 
		;



actualList	::= exp
		| actualList COMMA exp
		;

type		::= INT
		| BOOLEAN
		| STRING
		;

id  ::= ID
		;


