/**********************************************************************
 Java CUP specification for a parser for Simple programs
 **********************************************************************/

import java_cup.runtime.*;

parser code {:
   public void report_error(String message, Object info) {
        int line = 0;
        int column = 0;
        StringBuilder m = new StringBuilder("");
        if (info instanceof java_cup.runtime.Symbol) {
							java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
							String tokenName = sym.terminalNames[s.sym];
							// Special case EOF token program
							if (s.sym != sym.EOF) {
							line = ((TokenVal) s.value).linenum;
							column = ((TokenVal) s.value).charnum;
        }
        m.append(" : " + message + " - Token: " + tokenName + " value " + s.value);
        }
        Errors.fatal(line, column, m.toString());
    }
:};



/* Terminals (tokens returned by the scanner) */
terminal PUBLIC;
terminal CLASS;
terminal STATIC;
terminal IntNode INT;
terminal BooleanNode BOOLEAN;
terminal StringNode STRING;
terminal VoidNode VOID; // VoidNode was added.. try to comprehend why it did not exist..
terminal TRUE;
terminal FALSE;
terminal IfStmtNode IF;
terminal IfElseStmtNode ELSE;
terminal WhileStmtNode WHILE;
terminal DO;
terminal PRINT;
terminal RETURN;
terminal IdTokenVal     ID;
terminal IntLitTokenVal INTLITERAL;
terminal StringTokenVal STRINGLITERAL; // changed to StringTokenVal


terminal TokenVal       LCURLY, RCURLY;
terminal TokenVal       LPAREN, RPAREN;

terminal COMMA;
terminal TokenVal ASSIGN;
terminal SEMICOLON;
terminal PLUS, MINUS, TIMES, DIVIDE;
terminal NOT, AND, OR;
terminal EQUALS, NOTEQUALS, LESS, GREATER, LESSEQ, GREATEREQ;

terminal SWITCH;
terminal CASE;
terminal DEFAULT;

/* Non-terminals
 *
 * NOTE: You will need to add more nonterminals to this list as you
 *       add productions to the grammar below.
 */
non terminal ProgramNode      program;
non terminal ClassBodyNode    classBody;
non terminal Sequence         declList;
non terminal DeclNode	      	decl;
non terminal FieldDeclNode    fieldDecl;
non terminal TypeNode	     		type;
non terminal IdNode	      		id;

non terminal stmt;
non terminal MethodDeclNode   methodDecl;
non terminal FormalsListNode  formals;
non terminal FormalDeclNode   formalDecl;
non terminal MethodBodyNode   methodBody;
non terminal Sequence         varDeclList;
non terminal VarDeclNode      varDecl;
non terminal Sequence         stmtList;
non terminal actualList;
non terminal switchGroupList;
non terminal switchGroup;
non terminal switchLabel;
non terminal ExpNode          exp;
non terminal formalsList;
non terminal AssignStmtNode 	assignment;


precedence left LPAREN, RPAREN; 
precedence left OR;
precedence left AND;
precedence left EQUALS, NOTEQUALS;
precedence left LESS, GREATER, LESSEQ, GREATEREQ;
precedence left PLUS, MINUS; 
precedence left TIMES, DIVIDE; // Assoziativität links

precedence right NOT;
precedence right MINUS; // Unary minus

 
start with program;

/*
 * grammar with actions
 *
 * add more here
 */

program		::= PUBLIC CLASS id:a LCURLY classBody:b RCURLY
			{: RESULT = new ProgramNode(a, b); :}
		;

classBody	::= declList:e
		{: RESULT = new ClassBodyNode(new DeclListNode(e)); :}
		;

declList 	::= declList:a decl:b
		{: 
			System.out.println("Adding declaration to declList is actually " + a);
			a.addToEnd(b);
			RESULT = a;
		:}
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

decl	::= fieldDecl
		| methodDecl
		;

fieldDecl	::= STATIC type:e0 id:e1 SEMICOLON
		{: RESULT = new FieldDeclNode((TypeNode) e0, (IdNode) e1); :}
		;

methodDecl	::= PUBLIC STATIC VOID:a id:b formals:c methodBody:d // no return value
								{: RESULT = new MethodDeclNode(a, b, c, d); :}
                | PUBLIC STATIC INT:a id:b formals:c  methodBody:d // int return value allowed
								{: RESULT = new MethodDeclNode(a, b, c, d); :}
	        ;						

formals		::= LPAREN RPAREN
		| LPAREN formalsList RPAREN
		;

formalsList	::= formalDecl
		| formalDecl:e0 COMMA formalsList:e1
		{: System.out.println(e1.getClass().getName()); :}
		;

formalDecl	::= type:e0 id:e1
		{: RESULT = new FormalDeclNode(e0, e1 ); :}
		;

methodBody	::= LCURLY varDeclList stmtList RCURLY 
		;

varDeclList	::= varDeclList varDecl
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

varDecl		::= type:e0 id:e1 SEMICOLON
		{: RESULT = new VarDeclNode(e0, e1 ); :}
		;

stmtList	::= stmtList stmt
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;


/* the following rules are for the switch / case statement */

switchGroupList   ::= switchGroupList switchGroup
		| /* epsilon */
		{: RESULT = new Sequence(); :}
		;

switchGroup	::=   switchLabel stmtList
		;

switchLabel	::=   CASE exp COMMA
		|     				DEFAULT COMMA
		;      
		     
stmt		::= id:e0 ASSIGN exp:e1 SEMICOLON 
					{: RESULT = new AssignStmtNode(e0, e1); :}
	        | IF LPAREN exp:a RPAREN LCURLY stmtList:b RCURLY
					{: RESULT = new IfStmtNode(a, new StmtListNode(b)); :}
	        | IF LPAREN exp:a RPAREN LCURLY stmtList:b RCURLY ELSE LCURLY stmtList:c RCURLY
					{: RESULT = new IfElseStmtNode(a, new StmtListNode(b), new StmtListNode(c)); :}
					| PRINT LPAREN exp:e1 RPAREN SEMICOLON 
					{: RESULT = new PrintStmtNode(e1); :}
					;

exp		::= 
		| id:e
	  | INTLITERAL
	  | STRINGLITERAL
	  | TRUE
	  | FALSE
	  | LPAREN exp RPAREN
		;

functionCall ::= id LPAREN RPAREN // function call with no args
	  | id LPAREN actualList RPAREN // with args 
		;



actualList	::= exp
		| actualList COMMA exp
		;

type		::= INT {: RESULT = new IntNode(); :}
		| BOOLEAN {: RESULT = new BooleanNode(); :}
		| STRING {: RESULT = new StringNode(); :}
		| VOID {: RESULT = new VoidNode(); :}
		;

id  ::= ID:e
		{: RESULT = new IdNode(e.linenum, e.charnum, e.idVal); :}
		;


