/* The following code was generated by JFlex 1.7.0 */


/* User Code */
import java_cup.runtime.*; // defines the Symbol class
import java.util.LinkedList;

// The generated scanner will return a Symbol for each token that it finds.
// A Symbol contains an Object field named value; that field will be of type
// TokenVal, defined below.
//
// A TokenVal object contains the line number on which the token occurs as
// well as the number of the character on that line that starts the token.
// Some tokens (e.g., literals) also include the value of the token.

class TokenVal {
 // fields
    int linenum;
    int charnum;
 // constructor
    TokenVal(int l, int c) {
        linenum = l;
				charnum = c;
    }
}

class IntLitTokenVal extends TokenVal {
 // new field: the value of the integer literal
    int intVal;
 // constructor
    IntLitTokenVal(int l, int c, int val) {
        super(l,c);
				intVal = val;
    }
}

class StringTokenVal extends TokenVal {
 // new field: the value of the integer literal
    String str;
 // constructor
    StringTokenVal(int l, int c, String val) {
        super(l,c);
				str = val;
    }
}

// The following class is used to keep track of the character number at which
// the current token starts on its line.
class CharNum {
  static int num=1;
}
/* Options and declarations */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>simple.jlex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int BLOCKCOMMENT = 2;
  public static final int SLCOMMENT = 4;
  public static final int STRING = 6;
  public static final int STRING_ESCAPE = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\54\1\3\1\3\1\53\22\0\1\2\1\33\1\51"+
    "\1\50\1\0\1\30\1\34\1\0\1\0\1\0\1\26\1\25\1\35"+
    "\1\25\1\20\1\27\1\6\11\1\1\0\1\36\1\31\1\32\1\31"+
    "\2\0\13\4\1\4\1\4\1\4\4\4\1\14\1\4\1\4\5\4"+
    "\1\0\1\52\1\0\1\50\1\4\1\0\1\44\1\45\1\43\1\42"+
    "\1\10\1\37\1\46\1\41\1\23\2\4\1\24\1\17\1\13\1\21"+
    "\1\22\1\4\1\7\1\16\1\11\1\12\1\47\1\40\1\4\1\15"+
    "\1\4\1\0\1\5\1\0\7\0\1\3\u1fa2\0\1\3\1\3\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\1\1\1\2\5\4"+
    "\3\5\1\6\1\7\1\10\1\1\1\11\1\12\5\4"+
    "\1\13\3\14\2\15\1\16\1\17\1\2\1\17\1\2"+
    "\1\20\1\21\1\22\2\23\1\0\1\10\6\4\1\24"+
    "\1\25\1\26\1\6\5\4\1\27\5\4\1\30\22\4"+
    "\1\31\3\4\13\0\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\u0168\0\u0195\0\341\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276"+
    "\0\u02a3\0\341\0\u02d0\0\u02fd\0\u02fd\0\u02fd\0\u032a\0\341"+
    "\0\341\0\u0357\0\u0384\0\u03b1\0\u03de\0\u040b\0\341\0\341"+
    "\0\u02a3\0\u0438\0\341\0\u02a3\0\341\0\u0465\0\u0492\0\u04bf"+
    "\0\u0465\0\u0465\0\341\0\341\0\u02a3\0\341\0\u02a3\0\341"+
    "\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u0168\0\341"+
    "\0\341\0\341\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae\0\341"+
    "\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f\0\u0168\0\u07bc\0\u07e9"+
    "\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u0924\0\u0951"+
    "\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9"+
    "\0\u0168\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4"+
    "\0\u0c21\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\341";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\3\11\1\16\1\11\1\17\1\11\1\6\2\11"+
    "\1\20\1\11\1\21\1\22\1\23\1\22\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\11\1\32\1\11\1\33"+
    "\1\34\1\11\1\35\1\11\1\36\1\6\1\37\1\6"+
    "\2\10\1\40\1\7\1\10\1\0\1\40\1\41\1\13"+
    "\16\40\1\41\1\42\24\40\2\10\1\43\1\7\1\43"+
    "\1\0\1\43\1\44\1\13\16\43\1\44\25\43\1\0"+
    "\1\45\1\46\1\47\3\46\1\50\1\51\16\46\1\50"+
    "\6\46\1\52\13\46\1\52\1\53\1\54\3\0\1\7"+
    "\3\0\1\55\1\13\1\56\3\0\1\56\11\0\1\57"+
    "\105\0\1\7\4\0\1\7\50\0\1\10\50\0\2\10"+
    "\1\0\1\11\2\0\1\11\1\0\12\11\1\0\4\11"+
    "\12\0\11\11\6\0\1\7\3\0\1\60\1\13\47\0"+
    "\1\11\2\0\1\11\1\0\2\11\1\61\7\11\1\0"+
    "\4\11\12\0\11\11\6\0\1\11\2\0\1\11\1\0"+
    "\12\11\1\0\3\11\1\62\12\0\11\11\6\0\1\11"+
    "\2\0\1\11\1\0\3\11\1\63\3\11\1\64\2\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\12\11\1\0\4\11\12\0\1\11\1\65\7\11"+
    "\6\0\1\11\2\0\1\11\1\0\5\11\1\66\4\11"+
    "\1\0\4\11\12\0\1\67\10\11\6\0\1\7\4\0"+
    "\1\13\74\0\1\70\1\71\57\0\1\72\56\0\1\60"+
    "\21\0\1\11\2\0\1\11\1\0\12\11\1\0\4\11"+
    "\12\0\2\11\1\73\6\11\6\0\1\11\2\0\1\11"+
    "\1\0\2\11\1\74\7\11\1\0\1\67\3\11\12\0"+
    "\11\11\6\0\1\11\2\0\1\11\1\0\12\11\1\0"+
    "\3\11\1\75\12\0\5\11\1\62\3\11\6\0\1\11"+
    "\2\0\1\11\1\0\12\11\1\0\1\76\3\11\12\0"+
    "\11\11\6\0\1\11\2\0\1\11\1\0\12\11\1\0"+
    "\1\77\3\11\12\0\11\11\34\0\1\100\25\0\51\46"+
    "\4\0\1\46\1\47\4\46\1\47\42\46\4\0\1\46"+
    "\1\47\4\46\1\51\42\46\5\0\1\11\2\0\1\11"+
    "\1\0\3\11\1\101\6\11\1\0\4\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\10\11\1\102\1\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\103\10\11\1\0\4\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\10\11\1\104\1\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\12\11\1\0\2\11\1\105\1\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\3\11\1\106\6\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\12\11\1\0\2\11\1\107\1\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\12\11\1\0\4\11"+
    "\12\0\1\110\10\11\6\0\1\11\2\0\1\11\1\0"+
    "\12\11\1\0\4\11\12\0\5\11\1\111\3\11\6\0"+
    "\1\11\2\0\1\11\1\0\12\11\1\0\1\112\3\11"+
    "\12\0\11\11\6\0\1\11\2\0\1\11\1\0\12\11"+
    "\1\0\2\11\1\113\1\11\12\0\11\11\6\0\1\11"+
    "\2\0\1\11\1\0\4\11\1\114\5\11\1\0\4\11"+
    "\12\0\11\11\6\0\1\11\2\0\1\11\1\0\2\11"+
    "\1\67\7\11\1\0\4\11\12\0\11\11\6\0\1\11"+
    "\2\0\1\11\1\0\12\11\1\0\2\11\1\115\1\11"+
    "\12\0\11\11\6\0\1\11\2\0\1\11\1\0\3\11"+
    "\1\116\6\11\1\0\4\11\12\0\11\11\6\0\1\11"+
    "\2\0\1\11\1\0\3\11\1\117\6\11\1\0\4\11"+
    "\12\0\11\11\6\0\1\11\2\0\1\11\1\0\12\11"+
    "\1\0\3\11\1\102\12\0\11\11\6\0\1\11\2\0"+
    "\1\11\1\0\12\11\1\0\4\11\12\0\5\11\1\120"+
    "\3\11\6\0\1\11\2\0\1\11\1\0\10\11\1\121"+
    "\1\11\1\0\4\11\12\0\11\11\6\0\1\11\2\0"+
    "\1\11\1\0\12\11\1\0\3\11\1\122\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\12\11\1\0\4\11"+
    "\12\0\3\11\1\106\5\11\6\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\123\10\11\1\0\4\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\5\11\1\124\4\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\2\11\1\125\7\11\1\0\4\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\12\11\1\0\4\11"+
    "\12\0\4\11\1\126\4\11\6\0\1\11\2\0\1\11"+
    "\1\0\4\11\1\127\5\11\1\0\4\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\10\11\1\106\1\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\2\11\1\130\7\11\1\0\4\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\5\11\1\131\4\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\12\11\1\0\4\11\12\0\7\11\1\106\1\11"+
    "\6\0\1\11\2\0\1\11\1\0\11\11\1\132\1\0"+
    "\4\11\12\0\11\11\6\0\1\11\2\0\1\11\1\0"+
    "\12\11\1\0\4\11\12\0\2\11\1\67\6\11\6\0"+
    "\1\11\2\0\1\11\1\0\12\11\1\0\3\11\1\133"+
    "\12\0\11\11\6\0\1\11\2\0\1\11\1\0\12\11"+
    "\1\0\4\11\12\0\5\11\1\134\3\11\6\0\1\11"+
    "\2\0\1\11\1\0\12\11\1\135\4\11\12\0\11\11"+
    "\6\0\1\11\2\0\1\11\1\0\3\11\1\67\6\11"+
    "\1\0\4\11\12\0\11\11\6\0\1\11\2\0\1\11"+
    "\1\0\5\11\1\106\4\11\1\0\4\11\12\0\11\11"+
    "\26\0\1\136\45\0\1\137\53\0\1\140\63\0\1\141"+
    "\56\0\1\142\41\0\1\143\70\0\1\144\44\0\1\145"+
    "\52\0\1\146\67\0\1\147\43\0\1\150\41\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3420];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\4\1\1\11\6\1\1\11\5\1\2\11"+
    "\5\1\2\11\2\1\1\11\1\1\1\11\5\1\2\11"+
    "\1\1\1\11\1\0\1\11\7\1\3\11\5\1\1\11"+
    "\34\1\13\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
		//it's a stack - each new string gets pushed on top
    LinkedList<StringBuilder> stringBuffers = new LinkedList<StringBuilder>();

		//found out its probably not needed, however don't want to remove it :D 
		//probably everythings stored in StringTokenVal anyway


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case BLOCKCOMMENT: {
              Errors.fatal(yyline+1, CharNum.num,"Unterminated comment at EOF");
		yybegin(YYINITIAL); // Return to the initial state
            }  // fall though
            case 105: break;
            case SLCOMMENT: {
              Errors.fatal(yyline+1, CharNum.num,"Unterminated single line comment at EOF");
		yybegin(YYINITIAL); // Return to the initial state
            }  // fall though
            case 106: break;
            case STRING: {
              System.out.println("Unterminated string literal at EOF");
		System.out.println("Read until EOF: " + stringBuffers.get(stringBuffers.size() - 1).toString());
		Errors.fatal(yyline+1, CharNum.num,
					"Unterminated string literal at EOF");
		yybegin(YYINITIAL); // Return to the initial state
            }  // fall though
            case 107: break;
            default:
          { 						return new Symbol(sym.EOF); 
 }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { Errors.fatal(yyline+1, CharNum.num, "ignoring illegal character: " + yytext());
	CharNum.num++;
            } 
            // fall through
          case 27: break;
          case 2: 
            { // NOTE: the following computation of the integer value does NOT
	    //       check for overflow.  This must be changed.
			System.out.println("Found an integer literal: " + yytext());	
	    long val = Long.parseLong(yytext());
	    Symbol S = new Symbol(sym.INTLITERAL, new IntLitTokenVal(yyline+1, CharNum.num, (int) val));
	    CharNum.num += yytext().length();
	    return S;
            } 
            // fall through
          case 28: break;
          case 3: 
            { CharNum.num += yytext().length();
            } 
            // fall through
          case 29: break;
          case 4: 
            { System.out.println("Found identifier named: " + yytext());
										Symbol S = new Symbol(sym.IDENTIFIER, new TokenVal(yyline+1, CharNum.num)); //Symbol is not the right type
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 30: break;
          case 5: 
            { Symbol AOpsSymbol = null;
	switch (yytext()) {
		case "+":
			System.out.println("Found a plus operator");
			AOpsSymbol = new Symbol(sym.PLUS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
		case "-":
			System.out.println("Found a minus operator");
			AOpsSymbol = new Symbol(sym.MINUS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
		case "*":
			System.out.println("Found a multiplication operator");
			AOpsSymbol = new Symbol(sym.TIMES, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
		case "/":
			System.out.println("Found a division operator");
			AOpsSymbol = new Symbol(sym.DIVIDE, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return AOpsSymbol;
			
		default:
			//shouldn't be reached
			break;
	}
            } 
            // fall through
          case 31: break;
          case 6: 
            { Symbol ROpsSymbol = null;
	switch (yytext()) {
		case "<":
			System.out.println("Found a less-than operator");
			ROpsSymbol = new Symbol(sym.LESS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case ">":
			System.out.println("Found a greater-than operator");
			ROpsSymbol = new Symbol(sym.GREATER, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case "<=":
			System.out.println("Found a less-than-or-equal operator");
			ROpsSymbol = new Symbol(sym.LESSEQ, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case ">=":
			System.out.println("Found a greater-than-or-equal operator");
			ROpsSymbol = new Symbol(sym.GREATEREQ, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case "==":
			System.out.println("Found an equality operator");
			ROpsSymbol = new Symbol(sym.EQUALS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
		case "!=":
			System.out.println("Found a not-equal operator");
			ROpsSymbol = new Symbol(sym.NOTEQUALS, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return ROpsSymbol;
			
		default:
			//shouldn't be reached
			break;
	}
            } 
            // fall through
          case 32: break;
          case 7: 
            { System.out.println("Found an assignment operator");
	Symbol assign = new Symbol(sym.ASSIGN, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return assign;
            } 
            // fall through
          case 33: break;
          case 8: 
            { Symbol LOpsSymbol = null;
	switch (yytext()) {
		case "&&":
			System.out.println("Found a logical AND operator");
			LOpsSymbol = new Symbol(sym.AND, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return LOpsSymbol;
		case "||":
			System.out.println("Found a logical OR operator");
			LOpsSymbol = new Symbol(sym.OR, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return LOpsSymbol;
		case "!":
			System.out.println("Found a logical NOT operator");
			LOpsSymbol = new Symbol(sym.NOT, new TokenVal(yyline+1, CharNum.num));
			CharNum.num += yytext().length();
			return LOpsSymbol;
			
		default:
			//shouldn't be reached
			break;
	}
            } 
            // fall through
          case 34: break;
          case 9: 
            { System.out.println("Found a comma");
	Symbol comma = new Symbol(sym.COMMA, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return comma;
            } 
            // fall through
          case 35: break;
          case 10: 
            { System.out.println("Found a semicolon");
	Symbol semicolon = new Symbol(sym.SEMICOLON, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return semicolon;
            } 
            // fall through
          case 36: break;
          case 11: 
            { System.out.println("Start of a parsing string literal..");
		stringBuffers.add(new StringBuilder()); 
    yybegin(STRING); // Switch to STRING state
            } 
            // fall through
          case 37: break;
          case 12: 
            { CharNum.num += yytext().length(); // Consume any other characters inside comments
            } 
            // fall through
          case 38: break;
          case 13: 
            { System.out.println("Matched character in comment: " + yytext()); 
		CharNum.num += yytext().length(); // Consume charcters in single-line comment
            } 
            // fall through
          case 39: break;
          case 14: 
            { System.out.println("End of single-line comment"); //can't figure out why not working!!!!1 is test.sim corrupted??
				//cat -A test.sim shows new line character
				CharNum.num += yytext().length(); // Consume the newline character
				yybegin(YYINITIAL);
            } 
            // fall through
          case 40: break;
          case 15: 
            { stringBuffers.get(stringBuffers.size() - 1).append(yytext());
    CharNum.num += yytext().length(); // Consme any other characters inside strings
            } 
            // fall through
          case 41: break;
          case 16: 
            { //error illegal character in string
		Errors.fatal(yyline+1, CharNum.num,
					"illegal character in string: " + yytext());
            } 
            // fall through
          case 42: break;
          case 17: 
            { System.out.println("Resulting string literal: " + stringBuffers.get(stringBuffers.size() - 1).toString());
    yybegin(YYINITIAL); // Return to the initial state
    Symbol S = new Symbol(sym.STRINGLITERAL, new StringTokenVal(yyline+1, CharNum.num, stringBuffers.get(stringBuffers.size() - 1).toString()));
		CharNum.num += yytext().length();
    return S;
            } 
            // fall through
          case 43: break;
          case 18: 
            { //should work without - don't know why it doesn't
	yybegin(STRING_ESCAPE);
            } 
            // fall through
          case 44: break;
          case 19: 
            { System.out.println("Unterminated string literal" );

		switch(yytext()) {
			case "n":
				System.out.println("Found newline escape sequence");
				stringBuffers.get(stringBuffers.size() - 1).append('\n');
				CharNum.num += 2; // Reset character number at the start of a new line
				break;
			case "r":
				System.out.println("Found carriage return escape sequence");
				stringBuffers.get(stringBuffers.size() - 1).append('\r');
				CharNum.num += 2; // Reset character number at the start of a new line
				break;
			default: 
				// shouldn't be reached 
				break;
		}
		
    yybegin(STRING);
            } 
            // fall through
          case 45: break;
          case 20: 
            { Symbol FlowKeyWordSymbol = null;
  switch (yytext()) {
		case "if":
				System.out.println("Found an if");
				FlowKeyWordSymbol = new Symbol(sym.IF, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "else":
				System.out.println("Found an else");
				FlowKeyWordSymbol = new Symbol(sym.ELSE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "while":
				System.out.println("Found a while");
				FlowKeyWordSymbol = new Symbol(sym.WHILE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "do":
				System.out.println("Found a do");
				FlowKeyWordSymbol = new Symbol(sym.DO, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "switch":
				System.out.println("Found a switch");
				FlowKeyWordSymbol = new Symbol(sym.SWITCH, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "case":
				System.out.println("Found a case");
				FlowKeyWordSymbol = new Symbol(sym.CASE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		case "default":
				System.out.println("Found a default");
				FlowKeyWordSymbol = new Symbol(sym.DEFAULT, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return FlowKeyWordSymbol;
		default:
				// should not be reached
				break;
	}
            } 
            // fall through
          case 46: break;
          case 21: 
            { yybegin( BLOCKCOMMENT);
			CharNum.num += 2;
            } 
            // fall through
          case 47: break;
          case 22: 
            { yybegin( SLCOMMENT);
			CharNum.num += 2;
            } 
            // fall through
          case 48: break;
          case 23: 
            { yybegin(YYINITIAL);
			CharNum.num += 2;
            } 
            // fall through
          case 49: break;
          case 24: 
            { Symbol TypeSymbol = null;
	switch(yytext()) {
		case "int":
				System.out.println("Found type int");
				TypeSymbol = new Symbol(sym.INT, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "boolean":
				System.out.println("Found type boolean");
				TypeSymbol = new Symbol(sym.BOOLEAN, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "String":
				System.out.println("Found type String");
				TypeSymbol = new Symbol(sym.STRING, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "class":
				System.out.println("Found class keyword");
				TypeSymbol = new Symbol(sym.CLASS, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		case "void":
				System.out.println("Found void keyword");
				TypeSymbol = new Symbol(sym.VOID, new TokenVal(yyline+1, CharNum.num));
				CharNum.num += yytext().length();
				return TypeSymbol;
		default:
				// should not be reached
				break;
	}
            } 
            // fall through
          case 50: break;
          case 25: 
            { System.out.println("Found a return");
	Symbol S = new Symbol(sym.RETURN, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return S;
            } 
            // fall through
          case 51: break;
          case 26: 
            { System.out.println("Found a println");
	Symbol S = new Symbol(sym.PRINT, new TokenVal(yyline+1, CharNum.num));
	CharNum.num += yytext().length();
	return S;
            } 
            // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
