
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Feb 01 17:36:57 CST 2000
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {

  // assignment operator
  public static final int ASSIGN = 16;

  // arithmetic operators
  public static final int PLUS = 26;
  public static final int MINUS = 27;
  public static final int TIMES = 28; // multiply
  public static final int DIVIDE = 29;

  // keywords
  public static final int WHILE = 13;
  public static final int DO = 39;
  public static final int RETURN = 15;

  public static final int IF = 11;
  public static final int ELSE = 12;

  // punctuation
  public static final int SEMICOLON = 25;
  public static final int COMMA = 23;

  // logical operators
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int NOT = 30;

  // relational operators
  public static final int GREATER = 36;
  public static final int GREATEREQ = 38;
  public static final int NOTEQUALS = 34;
  public static final int LESSEQ = 37;
  public static final int LESS = 35;
  public static final int EQUALS = 33;

  // switch-case-default
  public static final int SWITCH = 41;
  public static final int CASE = 42;
  public static final int DEFAULT = 43;

  public static final int error = 1;

  // print
  public static final int PRINT = 14;

  // identifiers
  public static final int ID = 40;

  // literals
  public static final int INTLITERAL = 17;

  public static final int STRINGLITERAL = 18;

  // types
  public static final int VOID = 8;
  public static final int INT = 5;
  public static final int STRING = 7;
  public static final int BOOLEAN = 6;
  public static final int CLASS = 3;

  // Brackets
  public static final int LCURLY = 19;
  public static final int RCURLY = 20;
  public static final int LBRACKET = 44;
  public static final int RBRACKET = 45;

  // Parentheses
  public static final int LPAREN = 21;
  public static final int RPAREN = 22;

  // scope
  public static final int STATIC = 4;
  public static final int PUBLIC = 2;

  // other
  public static final int EOF = 0;

  // values
  public static final int TRUE = 9;
  public static final int FALSE = 10;

}
