/* The following code was generated by JFlex 1.7.0 */


/* User Code */
import java_cup.runtime.*; // defines the Symbol class

// The generated scanner will return a Symbol for each token that it finds.
// A Symbol contains an Object field named value; that field will be of type
// TokenVal, defined below.
//
// A TokenVal object contains the line number on which the token occurs as
// well as the number of the character on that line that starts the token.
// Some tokens (e.g., literals) also include the value of the token.

class TokenVal {
 // fields
    int linenum;
    int charnum;
 // constructor
    TokenVal(int l, int c) {
        linenum = l;
				charnum = c;
    }
}

class IntLitTokenVal extends TokenVal {
 // new field: the value of the integer literal
    int intVal;
 // constructor
    IntLitTokenVal(int l, int c, int val) {
        super(l,c);
				intVal = val;
    }
}


// The following class is used to keep track of the character number at which
// the current token starts on its line.
class CharNum {
  static int num=1;
}
/* Options and declarations */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>simple.jlex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\2\1\3\1\3\1\3\22\0\1\2\5\0\1\32"+
    "\4\0\1\7\1\0\1\6\1\16\1\0\12\1\1\0\1\4\1\0"+
    "\1\35\3\0\22\5\1\10\7\5\4\0\1\5\1\0\1\30\1\5"+
    "\1\27\1\26\1\14\1\31\1\5\1\34\1\23\2\5\1\25\1\15"+
    "\1\24\1\17\1\21\1\5\1\22\1\12\1\13\1\20\1\5\1\33"+
    "\1\5\1\11\1\5\12\0\1\3\u1fa2\0\1\3\1\3\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\6\5\1\1\1\10\4\5\1\11\2\5\1\12\2\5"+
    "\1\13\2\5\1\14\3\5\1\15\4\5\1\16\1\5"+
    "\1\0\1\17\12\0\1\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\36\0\74\0\132\0\36\0\170\0\74\0\36"+
    "\0\226\0\264\0\322\0\360\0\u010e\0\u012c\0\u014a\0\36"+
    "\0\u0168\0\u0186\0\u01a4\0\u01c2\0\170\0\u01e0\0\u01fe\0\36"+
    "\0\u021c\0\u023a\0\170\0\u0258\0\u0276\0\170\0\u0294\0\u02b2"+
    "\0\u02d0\0\170\0\u02ee\0\u030c\0\u032a\0\u0348\0\170\0\u0366"+
    "\0\u0384\0\170\0\u03a2\0\u03c0\0\u03de\0\u03fc\0\u041a\0\u0438"+
    "\0\u0456\0\u0474\0\u0492\0\u04b0\0\36";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\6\1\12\3\6\1\2\4\6\1\13\2\6"+
    "\1\14\1\15\1\16\1\6\1\17\2\6\1\20\37\0"+
    "\1\3\36\0\1\4\34\0\1\6\3\0\1\6\2\0"+
    "\6\6\1\0\13\6\1\0\2\6\2\0\1\6\3\0"+
    "\1\6\2\0\1\6\1\21\4\6\1\0\13\6\1\0"+
    "\2\6\2\0\1\6\3\0\1\6\2\0\6\6\1\0"+
    "\13\6\1\0\1\22\1\6\2\0\1\6\3\0\1\6"+
    "\2\0\6\6\1\0\5\6\1\23\5\6\1\0\2\6"+
    "\2\0\1\6\3\0\1\6\2\0\4\6\1\24\1\6"+
    "\1\0\1\25\12\6\1\0\2\6\2\0\1\6\3\0"+
    "\1\6\2\0\6\6\1\0\11\6\1\26\1\6\1\0"+
    "\2\6\2\0\1\6\3\0\1\6\2\0\6\6\1\0"+
    "\5\6\1\27\5\6\1\0\2\6\33\0\1\30\4\0"+
    "\1\6\3\0\1\6\2\0\2\6\1\31\3\6\1\0"+
    "\13\6\1\0\2\6\2\0\1\6\3\0\1\6\2\0"+
    "\6\6\1\0\4\6\1\32\6\6\1\0\2\6\2\0"+
    "\1\6\3\0\1\6\2\0\3\6\1\33\2\6\1\0"+
    "\13\6\1\0\2\6\2\0\1\6\3\0\1\6\2\0"+
    "\6\6\1\0\12\6\1\34\1\0\2\6\2\0\1\6"+
    "\3\0\1\6\2\0\2\6\1\35\3\6\1\0\13\6"+
    "\1\0\2\6\2\0\1\6\3\0\1\6\2\0\6\6"+
    "\1\0\7\6\1\36\3\6\1\0\2\6\2\0\1\6"+
    "\3\0\1\6\2\0\3\6\1\37\2\6\1\0\13\6"+
    "\1\0\2\6\2\0\1\6\3\0\1\6\2\0\3\6"+
    "\1\40\2\6\1\0\13\6\1\0\2\6\2\0\1\6"+
    "\3\0\1\6\2\0\6\6\1\0\11\6\1\41\1\6"+
    "\1\0\2\6\2\0\1\6\3\0\1\6\2\0\4\6"+
    "\1\42\1\6\1\0\13\6\1\0\2\6\2\0\1\6"+
    "\3\0\1\6\2\0\4\6\1\43\1\6\1\0\13\6"+
    "\1\0\2\6\2\0\1\6\3\0\1\6\2\0\6\6"+
    "\1\0\10\6\1\44\2\6\1\0\2\6\2\0\1\6"+
    "\3\0\1\6\2\0\6\6\1\0\1\6\1\45\11\6"+
    "\1\0\2\6\2\0\1\6\3\0\1\6\2\0\5\6"+
    "\1\46\1\0\13\6\1\0\2\6\2\0\1\6\3\0"+
    "\1\6\2\0\6\6\1\0\13\6\1\0\1\6\1\47"+
    "\2\0\1\6\3\0\1\6\2\0\6\6\1\0\6\6"+
    "\1\50\4\6\1\0\2\6\2\0\1\6\3\0\1\6"+
    "\2\0\6\6\1\51\13\6\1\0\2\6\2\0\1\6"+
    "\3\0\1\6\2\0\3\6\1\52\2\6\1\0\13\6"+
    "\1\0\2\6\20\0\1\53\36\0\1\54\30\0\1\55"+
    "\40\0\1\56\40\0\1\57\36\0\1\60\36\0\1\61"+
    "\36\0\1\62\24\0\1\63\47\0\1\64\34\0\1\65"+
    "\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1230];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\1\11\7\1\1\11"+
    "\7\1\1\11\20\1\1\0\1\1\12\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 						return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { Errors.fatal(yyline+1, CharNum.num,
					"ignoring illegal character: " + yytext());
					CharNum.num++;
            } 
            // fall through
          case 17: break;
          case 2: 
            { // NOTE: the following computation of the integer value does NOT
	    //       check for overflow.  This must be changed.
			System.out.println("Found an integer literal: " + yytext());	
	    long val = Long.parseLong(yytext());
	    Symbol S = new Symbol(sym.INTLITERAL, new IntLitTokenVal(yyline+1, CharNum.num, (int) val));
	    CharNum.num += yytext().length();
	    return S;
            } 
            // fall through
          case 18: break;
          case 3: 
            { CharNum.num += yytext().length();
            } 
            // fall through
          case 19: break;
          case 4: 
            { System.out.println("Found a semicolon");
										Symbol S = new Symbol(sym.SEMICOLON, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 20: break;
          case 5: 
            { System.out.println("Found a variable name: " + yytext());
										Symbol S = new Symbol(sym.IDENTIFIER, new TokenVal(yyline+1, CharNum.num)); //Symbol is not the right type
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 21: break;
          case 6: 
            { Symbol S = new Symbol(sym.MINUS, new TokenVal(yyline+1, CharNum.num));
	    		CharNum.num++;
	    		return S;
            } 
            // fall through
          case 22: break;
          case 7: 
            { Symbol S = new Symbol(sym.PLUS, new TokenVal(yyline+1, CharNum.num));
	    		CharNum.num++;
	    		return S;
            } 
            // fall through
          case 23: break;
          case 8: 
            { System.out.println("Found an assignment operator");
										Symbol S = new Symbol(sym.ASSIGN, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 24: break;
          case 9: 
            { System.out.println("Found a do");
										Symbol S = new Symbol(sym.DO, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 25: break;
          case 10: 
            { System.out.println("Found a &&");
										Symbol S = new Symbol(sym.AND, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 26: break;
          case 11: 
            { System.out.println("Found an int");
										Symbol S = new Symbol(sym.INT, new TokenVal(yyline+1, CharNum.num)); //int type is actually long
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 27: break;
          case 12: 
            { System.out.println("Found an and");
										Symbol S = new Symbol(sym.AND, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 28: break;
          case 13: 
            { System.out.println("Found a case");
										Symbol S = new Symbol(sym.CASE, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 29: break;
          case 14: 
            { System.out.println("Found a switch");
										Symbol S = new Symbol(sym.SWITCH, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 30: break;
          case 15: 
            { System.out.println("Found a default");
										Symbol S = new Symbol(sym.DEFAULT, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 31: break;
          case 16: 
            { System.out.println("Found a println");
										Symbol S = new Symbol(sym.SYSTEMOUTPRINTLN, new TokenVal(yyline+1, CharNum.num));
										CharNum.num += yytext().length();
										return S;
            } 
            // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
